-- 删除已存在的表
DROP TABLE IF EXISTS `${PROJECT_ID}.${DATASET}.CUSTOMER`;
DROP TABLE IF EXISTS `${PROJECT_ID}.${DATASET}.PART`;
DROP TABLE IF EXISTS `${PROJECT_ID}.${DATASET}.SUPPLIER`;
DROP TABLE IF EXISTS `${PROJECT_ID}.${DATASET}.PARTSUPP`;
DROP TABLE IF EXISTS `${PROJECT_ID}.${DATASET}.ORDERS`;
DROP TABLE IF EXISTS `${PROJECT_ID}.${DATASET}.LINEITEM`;
DROP TABLE IF EXISTS `${PROJECT_ID}.${DATASET}.NATION`;
DROP TABLE IF EXISTS `${PROJECT_ID}.${DATASET}.REGION`;

CREATE TABLE `${PROJECT_ID}.${DATASET}.CUSTOMER` (
    C_CUSTKEY       INTEGER,
    C_NAME          STRING,
    C_ADDRESS       STRING,
    C_NATIONKEY     INTEGER NOT NULL,
    C_PHONE         STRING,
    C_ACCTBAL       FLOAT64,
    C_MKTSEGMENT    STRING,
    C_COMMENT       STRING
);

CREATE TABLE `${PROJECT_ID}.${DATASET}.PART` (
    P_PARTKEY INTEGER,
    P_NAME STRING,
    P_MFGR STRING,
    P_BRAND STRING,
    P_TYPE STRING,
    P_SIZE INTEGER,
    P_CONTAINER STRING,
    P_RETAILPRICE NUMERIC,
    P_COMMENT STRING
);

CREATE TABLE `${PROJECT_ID}.${DATASET}.SUPPLIER` (
    S_SUPPKEY INTEGER,
    S_NAME STRING,
    S_ADDRESS STRING,
    S_NATIONKEY INTEGER NOT NULL,
    S_PHONE STRING,
    S_ACCTBAL NUMERIC,
    S_COMMENT STRING
);

CREATE TABLE `${PROJECT_ID}.${DATASET}.PARTSUPP` (
    PS_PARTKEY INTEGER NOT NULL,
    PS_SUPPKEY INTEGER NOT NULL,
    PS_AVAILQTY INTEGER,
    PS_SUPPLYCOST NUMERIC,
    PS_COMMENT STRING
);


CREATE TABLE `${PROJECT_ID}.${DATASET}.ORDERS` (
    O_ORDERKEY INTEGER,
    O_CUSTKEY INTEGER NOT NULL,
    O_ORDERSTATUS STRING,
    O_TOTALPRICE NUMERIC,
    O_ORDERDATE DATE,
    O_ORDERPRIORITY STRING,
    O_CLERK STRING,
    O_SHIPPRIORITY INTEGER,
    O_COMMENT STRING
);

CREATE TABLE `${PROJECT_ID}.${DATASET}.LINEITEM` (
    L_ORDERKEY INTEGER NOT NULL,
    L_PARTKEY INTEGER NOT NULL,
    L_SUPPKEY INTEGER NOT NULL,
    L_LINENUMBER INTEGER,
    L_QUANTITY NUMERIC,
    L_EXTENDEDPRICE NUMERIC,
    L_DISCOUNT NUMERIC,
    L_TAX NUMERIC,
    L_RETURNFLAG STRING,
    L_LINESTATUS STRING,
    L_SHIPDATE STRING,
    L_COMMITDATE STRING,
    L_RECEIPTDATE STRING,
    L_SHIPINSTRUCT STRING,
    L_SHIPMODE STRING,
    L_COMMENT STRING
);

CREATE TABLE `${PROJECT_ID}.${DATASET}.NATION` (
    N_NATIONKEY INTEGER,
    N_NAME STRING,
    N_REGIONKEY INTEGER,
    N_COMMENT STRING
);


CREATE TABLE `${PROJECT_ID}.${DATASET}.REGION` (
        R_REGIONKEY	INTEGER,
        R_NAME		STRING,
        R_COMMENT	STRING
);
